# ============================================================================
# A simple Ansible Collection example.
# --------------------------------------------------------------------------

include:
  - local: templates/pipeline-version.gitlab-ci.yml

  # --------------------------------------------------------------------------
  # NOTE: Below, we use 'local' include, since this file is tested as part of
  #       this project.  However, users of this 'image-pipeline' component
  #       will want to use the 'component' include syntax:
  #
  #       component: $GITLABCI_COMPONENT_CATALOG_PROJECT/ansible-collection@$GITLABCI_COMPONENT_CATALOG_REF
  - local: templates/ansible-collection.yml
    inputs:
      jobs_name_prefix: "[example] "
      collection_dir: examples/test_ansible_collection
      # Only one job in the Pipeline can create a Release... we defer to the
      # 'main' Pipeline:
      collection_release_enabled: false
