# ============================================================================
include:

  # --------------------------------------------------------------------------
  - local: templates/pipeline-version.job.yml

  # --------------------------------------------------------------------------
  - local: templates/image.pipeline.yml
    inputs:
      image_name: base-builder
      image_unit_test_enabled: false

  # --------------------------------------------------------------------------
  - local: templates/release.job.yml

  # --------------------------------------------------------------------------
  - local: .gitlab-ci/bashunit.gitlab-ci.yml

  # --------------------------------------------------------------------------
  - local: .gitlab-ci/stages.gitlab-ci.yml

  # --------------------------------------------------------------------------
  - local: templates/trigger-child-pipeline.job.yml
    inputs:
      local_path: examples/base-and-derived-images/.gitlab-ci.yml
      jobs_name_suffix: " (base-and-derived images)"
  - local: templates/trigger-child-pipeline.job.yml
    inputs:
      local_path: examples/helm-chart/.gitlab-ci.yml
      jobs_name_suffix: " (helm chart)"
  - local: templates/trigger-child-pipeline.job.yml
    inputs:
      local_path: examples/simple-image/.gitlab-ci.yml
      jobs_name_suffix: " (simple image)"


# ============================================================================
workflow:
  name: Core Pipelines
  rules:
    - !reference [.rules//prevent-duplicate-pipelines,  rules]



# ============================================================================
bash unit-test:
  extends: .bash-unit-test
  variables:
    BASH_UNITTEST_TEST_PATH: tests/*.tests.sh
