# NOTE: All jobs in this project's Pipeline use the source code contained in
#       the pulled repository (vice the source code present in the image).
#
#       Basically, we're dog-fooding the build pipeline using the current Git
#       ref.
include:
  - local: pipelines/.configure-access.yaml
  - local: pipelines/.stages.yaml
  - local: pipelines/.defaults.yaml
  - local: pipelines/tarfile-package.pipeline.yaml

variables:
  PYTHONPATH: ./src
  GITLABCI_SCRIPT: uv run ./src/gitlab-ci.py
  LOCAL_HELM_DEPENDENCIES: ./data/helm-repo-dependencies.yaml

.configure-podman-access:
  script:
    - export EPHEMERAL_REGISTRY_CONF_PATH=/etc/containers/registries.conf.d/ephemeral-registry.conf
    - |
      if [[ -n "${GITLABCI_EPHEMERAL_REGISTRY_URL}" && ! -f ${EPHEMERAL_REGISTRY_CONF_PATH} ]]; then
        cat > ${EPHEMERAL_REGISTRY_CONF_PATH} <<__EOF
          [[registry]]
          location = "${GITLABCI_EPHEMERAL_REGISTRY_URL}"
          insecure = true
      __EOF
      fi
    - podman login ${CI_REGISTRY} --username ${CI_REGISTRY_USER}
                                  --password ${CI_REGISTRY_PASSWORD}


# ----------------------------------------------------------------------------
# Checks this project's settings for conformance.
check-project-settings:
  image: ${GITLABCI_DEFAULT_IMAGE_NAME}:${GITLABCI_DEFAULT_IMAGE_VERSION}
  stage: .pre
  script:
    - ${GITLABCI_SCRIPT} project --expectations ./data/project-expectations.yaml ${CI_PROJECT_ID}
  allow_failure: true


# ----------------------------------------------------------------------------
# Checks this pipeline's version information.
calculate-pipeline-version:
  image: ${GITLABCI_DEFAULT_IMAGE_NAME}:${GITLABCI_DEFAULT_IMAGE_VERSION}
  stage: .pre
  script:
    - id
    - pwd
    - ls -alF
    - ${GITLABCI_SCRIPT} pipeline version --to-file ./version.env --force
  artifacts:
    reports:
      dotenv: ./version.env


# ----------------------------------------------------------------------------
# Builds and saves the Python package for this project
build-python-package:
  image: ${GITLABCI_DEFAULT_IMAGE_NAME}:${GITLABCI_DEFAULT_IMAGE_VERSION}
  stage: build
  script:
    - ${GITLABCI_SCRIPT} python --project-root .
                                --build-type uv
                                build
  needs: []
  artifacts:
    paths:
      - ./dist
    expire_in: 1 week


# ----------------------------------------------------------------------------
# Builds and saves the OCI image for this project
build-image:
  image: ${GITLABCI_DEFAULT_IMAGE_NAME}:${GITLABCI_DEFAULT_IMAGE_VERSION}
  stage: build
  before_script:
    - !reference ['.configure-podman-access', 'script']
  script:
    - mkdir -p ./.build/images
    - export PYTHONPATH=./src:${PYTHONPATH}
    - |
      if [[ -n "${GITLABCI_EPHEMERAL_REGISTRY_URL}" ]];  then
        ${GITLABCI_SCRIPT} image build  --push-registry ${GITLABCI_EPHEMERAL_REGISTRY_URL} \
                                        --output-dir ./.build/images
      else
        ${GITLABCI_SCRIPT} image build  --save-file \
                                        --output-dir ./.build/images
      fi
  needs: []
  artifacts:
    paths:
      - ./.build/images
    expire_in: 1 week


# # ----------------------------------------------------------------------------
# # Tests the data preparation job for ML Pipelines
# prepare-data:
#   image: ${GITLABCI_DEFAULT_IMAGE_NAME}:${GITLABCI_DEFAULT_IMAGE_VERSION}
#   stage: build
#   variables:
#     PYTHONPATH: ./src:./test
#   script:
#     - ${GITLABCI_SCRIPT}  ml
#                           data
#                           prepare
#                           gitlabci_test.ml.data.example_data_prepare.TrainTestData
#   needs: []
#   artifacts:
#     paths:
#       - ./.data/*.npz


# ----------------------------------------------------------------------------
# Unit tests this project
unittest:
  image: ${GITLABCI_DEFAULT_IMAGE_NAME}:${GITLABCI_DEFAULT_IMAGE_VERSION}
  stage: test
  script:
    - ${GITLABCI_SCRIPT} python --project-root .
                                --build-type uv
                                test
  needs: []
  artifacts:
    paths:
      - ./.build/test-results
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./.build/test-results/coverage.xml
      junit: ./.build/test-results/unit-tests.xml
    expire_in: 1 week


# ----------------------------------------------------------------------------
# Tests (verifies) the ability to build/push Helm Charts
helmtest:
  image: ${GITLABCI_DEFAULT_IMAGE_NAME}:${GITLABCI_DEFAULT_IMAGE_VERSION}
  stage: test
  script:
    - mkdir -p ./.build/charts
    - ${GITLABCI_SCRIPT} helm  --dependencies ${LOCAL_HELM_DEPENDENCIES}
                                build  --chart-dir test/helm
                                      --output-dir ./.build/charts
    - ${GITLABCI_SCRIPT} helm  --dependencies ${LOCAL_HELM_DEPENDENCIES}
                                push   --channel devel
                                      ./.build/charts/*.tgz
  needs: []


# ----------------------------------------------------------------------------
# Pushes this project's image(s) to the container registry
push-image:
  image: ${GITLABCI_DEFAULT_IMAGE_NAME}:${GITLABCI_DEFAULT_IMAGE_VERSION}
  stage: publish
  before_script:
    - !reference ['.configure-podman-access', 'script']
  script:
    - ${GITLABCI_SCRIPT} image push ./.build/images/*.yaml
  needs:
    - build-image
    - unittest
    - helmtest
  rules:
    - if: $CI_COMMIT_REF_PROTECTED =~ /true/
    - if: $GITLABCI_PUSH_IMAGE_FORCE =~ /true/


# ----------------------------------------------------------------------------
# Pushes this project's Python package to the package registry
push-python-package:
  image: ${GITLABCI_DEFAULT_IMAGE_NAME}:${GITLABCI_DEFAULT_IMAGE_VERSION}
  stage: publish
  script:
    - ${GITLABCI_SCRIPT}  --verbose  python --project-root .
                                            --build-type uv
                                            push
  needs:
    - build-python-package
    - unittest
    - helmtest
  rules:
    - if: $CI_COMMIT_REF_PROTECTED =~ /true/
    - if: $GITLABCI_PUSH_PYTHON_FORCE =~ /true/


# ----------------------------------------------------------------------------
# Test creating a tarfile of this project
build-tar-package:
  extends: .build-tar-package


# ----------------------------------------------------------------------------
# Push this projects tarfile package to the package registry
push-tar-package:
  extends: .push-tar-package
