repos:
  - repo: local
    hooks:
      - id: block-banned-string
        name: Check for forbidden strings
        entry: 'set\s+-x'
        language: pygrep
        types:
          - text
  - repo: https://gitlab.westsidestreet.net/kerrys-learning-lab/development-environment/pre-commit-hooks
    rev: v0.2.0
    hooks:
      - id: gitlab-ci-lint
