# ============================================================================
variables:
  TF_IMAGE_TAG: 1.15.6


# ============================================================================
.terraform-base:
  image: registry.westsidestreet.net/kerrys-learning-lab/devsecops/gitlab-builder/terraform:0.2
  variables:
    TF_DIR: .
    TF_IN_AUTOMATION: true
    TF_INPUT: false
    TF_S3_BACKEND: false
    TF_S3_ACCESS_KEY: ''
    TF_S3_SECRET_KEY: ''
  before_script:
    - |
      # --- terraform-base ---------------------------------------------------
      TF_INIT_CLI_ARGS=()
      TF_INIT_CLI_ARGS+=(-input=false)

      if [[ "${TF_S3_BACKEND}" == "true" ]]; then
        TF_INIT_CLI_ARGS+=(-backend-config=config.s3.tfbackend)
        TF_INIT_CLI_ARGS+=(-backend-config="access_key=${TF_S3_ACCESS_KEY}")
        TF_INIT_CLI_ARGS+=(-backend-config="secret_key=${TF_S3_SECRET_KEY}")
      fi

      terraform -chdir=${TF_DIR}  init  ${TF_INIT_CLI_ARGS[@]}


# ============================================================================
.terraform-validate:
  extends: .terraform-base
  stage: test
  script:
    - |
      # --- terraform-validate -----------------------------------------------
      terraform -chdir=${TF_DIR} fmt -check -recursive -diff
      terraform -chdir=${TF_DIR} validate


# ============================================================================
.terraform-plan:
  stage: build
  extends: .terraform-base
  variables:
    TF_PLAN_ARTIFACT_BINARY: tfplan
    TF_PLAN_ARTIFACT_TEST: tfplan.txt
  script:
    - |
      # --- terraform-plan ---------------------------------------------------
      TF_PLAN_CLI_ARGS=()
      TF_PLAN_CLI_ARGS+=(-input=false)
      TF_PLAN_CLI_ARGS+=(-out=tfplan)

      for var in ${TF_EXTRA_VARS}; do
        TF_PLAN_CLI_ARGS+=(-var "${var}")
      done

      terraform -chdir=${TF_DIR} plan ${TF_PLAN_CLI_ARGS[@]}
      terraform -chdir=${TF_DIR} show tfplan | tee tfplan.txt
  artifacts:
    paths:
      - $TF_PLAN_ARTIFACT_BINARY
      - $TF_PLAN_ARTIFACT_TEST
    expire_in: 7 days
    when: always


# ============================================================================
.terraform-apply:
  extends: .terraform-base
  variables:
    TF_PLAN_ARTIFACT_BINARY: tfplan
  script:
    - |
      # --- terraform-apply --------------------------------------------------
      terraform -chdir=${TF_DIR} apply -input=false ${TF_PLAN_ARTIFACT_BINARY}
      terraform -chdir=${TF_DIR} output
