# ============================================================================
.ansible-collection-build:
  image: $GITLABCI_DEFAULT_ANSIBLE_BUILDER_IMAGE:$GITLABCI_DEFAULT_ANSIBLE_BUILDER_IMAGE_REF
  variables:
    ANSIBLE_COLLECTION_DIR: .
    ANSIBLE_COLLECTION_BUILD_DIR: .ansible-collection-build
  script:
    - |
      # --- ansible-collection-build -----------------------------------------

      yq -i ".version = \"${GITLABCI_SEMANTIC_VERSION}\"" ${ANSIBLE_COLLECTION_DIR}/galaxy.yml

      if [[ -f ${ANSIBLE_COLLECTION_DIR}/ansible.cfg ]]; then
        export ANSIBLE_CONFIG=${ANSIBLE_COLLECTION_DIR}/ansible.cfg
      fi

      mkdir -p ${ANSIBLE_COLLECTION_BUILD_DIR}
      ansible-galaxy collection build --output-path ${ANSIBLE_COLLECTION_BUILD_DIR}  ${ANSIBLE_COLLECTION_DIR}
  artifacts:
    paths:
      - $ANSIBLE_COLLECTION_BUILD_DIR
    when: always


# ============================================================================
.ansible-lint:
  image: $GITLABCI_DEFAULT_ANSIBLE_BUILDER_IMAGE:$GITLABCI_DEFAULT_ANSIBLE_BUILDER_IMAGE_REF
  variables:
    ANSIBLE_COLLECTION_DIR: .
    ANSIBLE_LINT_STRICT: true
  script:
    - |
      # --- ansible-collection-lint ------------------------------------------

      ANSIBLE_LINT_CLI_ARGS=()

      if [[ "${ANSIBLE_LINT_STRICT}" == "true" ]]; then
        ANSIBLE_LINT_CLI_ARGS+=(--strict)
      fi

      ansible-lint  ${ANSIBLE_LINT_CLI_ARGS[@]}  ${ANSIBLE_COLLECTION_DIR}
