# ----------------------------------------------------------------------------
.utility//print-settings-table:
  script:
    - |
      if [[ -n "${JOB_SETTINGS_TABLE[@]}" ]]; then
        ROWS="==========;==========\n"
        for row in "${JOB_SETTINGS_TABLE[@]}"; do
          ROWS+="${row}"'\n'
        done
        printf "${ROWS}" | column --table  \
                                  --separator ';' \
                                  --output-separator ' | '  \
                                  --table-column name=Setting \
                                  --table-column name=Value
      fi


# ----------------------------------------------------------------------------
.utility//protected-ref:
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"


# ----------------------------------------------------------------------------
.utility//protected-tag:
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_TAG


# ----------------------------------------------------------------------------
.utility//not-a-merge-request:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never


# ----------------------------------------------------------------------------
.utility//functions:
  script:
    - |
      # utility//functions (declarations)
      function title_case() {
        echo "$*" | sed -E 's/(.)/\L\1/g; s/\b(.)/\U\1/g'
      }
