include:
  - local: templates/image-pipeline.yml
    inputs:
      jobs_prefix: "[example] "
      jobs_suffix: " (simple)"
      image_name: gitlab-ci/examples/simple-image
      image_build_context: examples/simple-image
      image_unit_test_enabled: false
      image_structure_test_enabled: false
