include:
  - local: templates/image-pipeline.yml
    inputs:
      image-name: gitlab-ci/examples/simple-image
      image-build-context: examples/simple-image
      image-unit-test-enabled: false
      image-structure-test-enabled: false
