# ============================================================================
# This Pipeline start an environment and schedules it to stop after a
# pre-determined amount of time.
spec:
  inputs:

    # ------------------------------------------------------------------------
    # Apply to TF, generally:
    tf_dir:
      description: Directory (relative to repository root) of the Terraform
                   scripts
      type: string
      default: .
    tf_environment:
      description: Environment controlled by this TF Pipeline (required)
      type: string
    tf_s3_backend:
      description: If true, the S3 backend will be used
      type: boolean
      default: false
    tf_s3_access_key:
      description: The S3 access key for the TF backend
      type: string
      default: ''
    tf_s3_secret_key:
      description: The S3 secret key for the TF backend
      type: string
      default: ''


    # ------------------------------------------------------------------------
    # Plan Job(s):
    tf_plan_stage:
      description: Assigns the Pipeline stage for the 'terraform plan' Job
      type: string
      default: build


    # ------------------------------------------------------------------------
    # Validate Job:
    tf_validate_stage:
      description: Assigns the Pipeline stage for the 'terraform validate' Job
      type: string
      default: test


    # ------------------------------------------------------------------------
    # Start Job:
    tf_start_stage:
      description: Assigns the Pipeline stage for the 'terraform start' Job
      type: string
      default: deploy
    tf_start_when:
      description: Controls when the 'terraform start' Job executes
      type: string
      options:
        - on_success
        - manual
      default: on_success
    tf_start_job_extends:
      description: Base Job from which the 'terraform start' Job should extend
      type: string
      default: .terraform-apply


    # ------------------------------------------------------------------------
    # Stop Job:
    tf_stop_stage:
      description: Assigns the Pipeline stage for the 'terraform stop' Job
      type: string
      default: deploy
    tf_stop_when:
      description: Controls when the 'terraform stop' Job executes
      type: string
      default: 4 hours
    tf_stop_job_extends:
      description: Base Job from which the 'terraform stop' Job should extend
      type: string
      default: .terraform-apply


    # ------------------------------------------------------------------------
    # These settings affect Job names for all Jobs instantiated by the component
    jobs_name_prefix:
      description: Optional prefix for the Job names
      type: string
      default: ''
    jobs_name_suffix:
      description: Optional suffix for the Job names
      type: string
      default: ''


  # --------------------------------------------------------------------------
  # Propagate component metadata
  component:
    - name
    - version
    - reference


---


# ============================================================================
include:
  - local: templates/pipeline-version.job.yml
  - local: .gitlab-ci/lib/stages.gitlab-ci.yml
  - local: .gitlab-ci/lib/rules.gitlab-ci.yml
  - local: .gitlab-ci/jobs/.terraform.gitlab-ci.yml


# ============================================================================
"$[[ inputs.jobs_name_prefix ]]terraform plan$[[ inputs.jobs_name_suffix ]]":
  extends: .terraform-plan
  stage: $[[ inputs.tf_plan_stage ]]
  variables:
    TF_EXTRA_VARS: action=start
    TF_DIR: $[[ inputs.tf_dir ]]
    TF_S3_BACKEND: $[[ inputs.tf_s3_backend ]]
    TF_S3_ACCESS_KEY: $[[ inputs.tf_s3_access_key ]]
    TF_S3_SECRET_KEY: $[[ inputs.tf_s3_secret_key ]]
  rules:
    - !reference [.rules//prevent-duplicate-pipelines,  rules]
    - when: on_success


# ============================================================================
"$[[ inputs.jobs_name_prefix ]]terraform validate$[[ inputs.jobs_name_suffix ]]":
  extends: .terraform-validate
  stage: $[[ inputs.tf_validate_stage ]]
  variables:
    TF_DIR: $[[ inputs.tf_dir ]]
    TF_S3_BACKEND: $[[ inputs.tf_s3_backend ]]
    TF_S3_ACCESS_KEY: $[[ inputs.tf_s3_access_key ]]
    TF_S3_SECRET_KEY: $[[ inputs.tf_s3_secret_key ]]
  rules:
    - !reference [.rules//prevent-duplicate-pipelines,  rules]
    - when: on_success


# ============================================================================
"$[[ inputs.jobs_name_prefix ]]terraform start$[[ inputs.jobs_name_suffix ]]":
  extends: $[[ inputs.tf_start_job_extends ]]
  stage: $[[ inputs.tf_start_stage ]]
  variables:
    TF_DIR: $[[ inputs.tf_dir ]]
    TF_S3_BACKEND: $[[ inputs.tf_s3_backend ]]
    TF_S3_ACCESS_KEY: $[[ inputs.tf_s3_access_key ]]
    TF_S3_SECRET_KEY: $[[ inputs.tf_s3_secret_key ]]
  environment:
    name: $[[ inputs.tf_environment ]]
    action: start
    on_stop: "$[[ inputs.jobs_name_prefix ]]terraform stop$[[ inputs.jobs_name_suffix ]]"
    auto_stop_in: $[[ inputs.tf_stop_when ]]
  resource_group: $[[ inputs.tf_environment ]]
  rules:
    - !reference [.rules//prevent-duplicate-pipelines,  rules]
    - !reference [.rules//only-default-branch,          rules]
    - when: $[[ inputs.tf_start_when ]]


# ============================================================================
"$[[ inputs.jobs_name_prefix ]]terraform stop$[[ inputs.jobs_name_suffix ]]":
  extends: $[[ inputs.tf_start_job_extends ]]
  stage: $[[ inputs.tf_stop_stage ]]
  variables:
    TF_DIR: $[[ inputs.tf_dir ]]
    TF_S3_BACKEND: $[[ inputs.tf_s3_backend ]]
    TF_S3_ACCESS_KEY: $[[ inputs.tf_s3_access_key ]]
    TF_S3_SECRET_KEY: $[[ inputs.tf_s3_secret_key ]]
  environment:
    name: $[[ inputs.tf_environment ]]
    action: stop
  resource_group: $[[ inputs.tf_environment ]]
  rules:
    - !reference [.rules//prevent-duplicate-pipelines,  rules]
    - !reference [.rules//only-default-branch,          rules]
    - when: manual
