include:
  - project: $GITLABCI_DEFAULT_PIPELINE_PROJECT
    ref: $GITLABCI_DEFAULT_PIPELINE_REF
    file:
      - pipelines/.stages.yaml
      - pipelines/.defaults.yaml

variables:
  UV_INDEX_WESTSIDESTREET_USERNAME: gitlab-ci-token
  UV_INDEX_WESTSIDESTREET_PASSWORD: $CI_JOB_TOKEN


# ----------------------------------------------------------------------------
# Fails the Pipeline if the lockfile is stale
check-uv-lockfile:
  stage: .pre
  script:
    - uv lock --check --no-sources
  rules:
    - exists:
        - pyproject.toml


# ----------------------------------------------------------------------------
# Builds and saves a Python package for this project
.build-python-package:
  stage: build
  script:
    - gitlab-ci  python --project-root ${GITLABCI_PYTHON_BUILD_CONTEXT:-.}
                        --build-type ${GITLABCI_PYTHON_BUILD_TYPE:-uv}
                        build
  artifacts:
    paths:
      - ./dist
    expire_in: 1 week


# ----------------------------------------------------------------------------
# Runs the unit tests for the Python package
.test-python-package:
  stage: test
  before_script:
    - |
      if [[ -f pyproject.toml ]]; then
        uv sync --no-sources
      fi
  script:
    - gitlab-ci  python --project-root ${GITLABCI_PYTHON_BUILD_CONTEXT:-.}
                        --build-type ${GITLABCI_PYTHON_BUILD_TYPE:-uv}
                        test  --validate-only
    - uv run --no-sources pytest
  rules:
    - if: $GITLABCI_PYTHON_UNITTESTS == true
  needs: []
  artifacts:
    reports:
      junit: .build/test-results/unit-tests.xml
      coverage_report:
        coverage_format: cobertura
        path: .build/test-results/coverage.xml
    paths:
      - ./.build/test-results
    expire_in: 1 week
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'


# ----------------------------------------------------------------------------
# Pushes this project's Python package to the container registry
.push-python-package:
  stage: publish
  script:
    - gitlab-ci  python --project-root ${GITLABCI_PYTHON_BUILD_CONTEXT:-.}
                        --build-type ${GITLABCI_PYTHON_BUILD_TYPE:-uv}
                        push
  rules:
    - if: $CI_COMMIT_REF_PROTECTED =~ /true/
    - if: $GITLABCI_PUSH_PYTHON_FORCE =~ /true/
