# ============================================================================
# A simple Helm Chart example, including helmunit tests.
# --------------------------------------------------------------------------

include:
  - local: templates/pipeline-version.job.yml


  # --------------------------------------------------------------------------
  # NOTE: Below, we use 'local' include, since this file is tested as part of
  #       this project.  However, users of this 'helm-chare.pipeline' component
  #       will want to use the 'component' include syntax:
  #
  #       component: $GITLABCI_COMPONENT_CATALOG_PROJECT/helm-pipeline@$GITLABCI_COMPONENT_CATALOG_REF
  - local: templates/helm-chart.pipeline.yml
    inputs:
      jobs_name_prefix: "[example] "
      helm_chart_dir: examples/helm-chart
      helm_unit_test_chart_dir: examples/helm-chart
      helm_release_enabled: false
