# ============================================================================
.ansible-base:
  image: $GITLABCI_DEFAULT_ANSIBLE_BUILDER_IMAGE:$GITLABCI_DEFAULT_ANSIBLE_BUILDER_IMAGE_REF
  variables:
    ANSIBLE_DIR: .
    ANSIBLE_CFG_FILE: ansible.cfg
    ANSIBLE_INVENTORY_PATH: ''
    ANSIBLE_HOST_FILTER: ''
  before_script:
    - !reference [.utilities//load-all,     script]
    - !reference [.auth//ssh-remote-access, script]
    - |
      # --- ansible-base -----------------------------------------------------
      if [[ -f ${ANSIBLE_DIR}/${ANSIBLE_CFG_FILE} ]]; then
        export ANSIBLE_CONFIG=${ANSIBLE_DIR}/${ANSIBLE_CFG_FILE}
      fi

      if [[ -n "${ANSIBLE_REQUIREMENTS_FILE}" ]]; then
        ansible-galaxy collection install --requirements-file ${ANSIBLE_DIR}/${ANSIBLE_REQUIREMENTS_FILE}
      fi

      ANSIBLE_CLI_ARGS=()

      if [[ -n "${ANSIBLE_INVENTORY_PATH}" ]]; then
        ANSIBLE_CLI_ARGS+=(--inventory ${ANSIBLE_DIR}/${ANSIBLE_INVENTORY_PATH})
      fi

      if [[ -n "${ANSIBLE_HOST_FILTER}" ]]; then
        ANSIBLE_CLI_ARGS+=(--limit "${ANSIBLE_HOST_FILTER}")
      fi


# ============================================================================
.ansible-test-ssh-connection:
  extends: .ansible-base
  variables:
    ANSIBLE_DIR: .
    ANSIBLE_INVENTORY_PATH: ''
    ANSIBLE_REQUIREMENTS_FILE: ''
    ANSIBLE_HOST_FILTER: ''
    ANSIBLE_REMOTE_USER: gitlab-runner
    SSH_TEST_COMMAND: uname -a
    SSH_TEST_OPTIONS: -o BatchMode=yes
  script:
    - |
      # --- ansible-test-ssh-connection --------------------------------------
      ANSIBLE_CLI_ARGS+=(--list-hosts)

      # List the inventory (hosts), skipping the first line, which is a header
      ANSIBLE_HOSTS=$(ansible all "${ANSIBLE_CLI_ARGS[@]}" | tail -n +2)

      for host in ${ANSIBLE_HOSTS}; do
        if [[ -n "${GITLABCI_DOMAIN_NAME}" ]]; then
          host=${host}.${GITLABCI_DOMAIN_NAME}
        fi

        fn_log_info "ssh ${ANSIBLE_REMOTE_USER}@${host}..."
        ssh  ${SSH_TEST_OPTIONS}  ${ANSIBLE_REMOTE_USER}@${host}  ${SSH_TEST_COMMAND}
      done


# ============================================================================
.ansible-collection-build:
  extends: .ansible-base
  variables:
    ANSIBLE_DIR: .
    ANSIBLE_BUILD_DIR: .ansible-collection-build
    ANSIBLE_CFG_FILE: ansible.cfg
  script:
    - |
      # --- ansible-collection-build -----------------------------------------
      yq -i ".version = \"${GITLABCI_SEMANTIC_VERSION}\"" ${ANSIBLE_DIR}/galaxy.yml

      mkdir -p ${ANSIBLE_BUILD_DIR}
      ansible-galaxy collection build --output-path ${ANSIBLE_BUILD_DIR}  ${ANSIBLE_DIR}
  artifacts:
    paths:
      - $ANSIBLE_BUILD_DIR
    when: always


# ============================================================================
.ansible-lint:
  extends: .ansible-base
  variables:
    ANSIBLE_DIR: .
    ANSIBLE_FILE: ''
    ANSIBLE_LINT_STRICT: true
    ANSIBLE_CFG_FILE: ansible.cfg
    ANSIBLE_REQUIREMENTS_FILE: ''
  script:
    - |
      # --- ansible-lint -----------------------------------------------------
      ANSIBLE_LINTABLE_PATH=${ANSIBLE_DIR}

      if [[ -n "${ANSIBLE_FILE}" ]]; then
        ANSIBLE_LINTABLE_PATH+=/${ANSIBLE_FILE}
      fi

      ANSIBLE_CLI_ARGS+=(--profile=production)

      if [[ "${ANSIBLE_LINT_STRICT}" == "true" ]]; then
        ANSIBLE_CLI_ARGS+=(--strict)
      fi

      export PYTHONWARNINGS=ignore
      ansible-lint  ${ANSIBLE_CLI_ARGS[@]}  ${ANSIBLE_LINTABLE_PATH}


# ============================================================================
.ansible-playbook-run:
  extends: .ansible-base
  stage: publish
  variables:
    ANSIBLE_DIR: .
    ANSIBLE_INVENTORY_PATH: ''
    ANSIBLE_CFG_FILE: ansible.cfg
    ANSIBLE_REQUIREMENTS_FILE: ''
    ANSIBLE_HOST_FILTER: ''
    ANSIBLE_DRY_RUN: true
    ANSIBLE_LOG_PATH: ./.ansible-run/ansible.log
  script:
    - |
      # --- ansible-playbook-run ---------------------------------------------
      if [[ -n "${ANSIBLE_INVENTORY_PATH}" ]]; then
        ANSIBLE_CLI_ARGS+=(--inventory ${ANSIBLE_DIR}/${ANSIBLE_INVENTORY_PATH})
      fi

      if [[ "${ANSIBLE_DRY_RUN}" == "true" ]]; then
        ANSIBLE_CLI_ARGS+=(--check)
      fi

      if [[ -n "${ANSIBLE_REMOTE_USER}" ]]; then
        ANSIBLE_CLI_ARGS+=(--user ${ANSIBLE_REMOTE_USER})
      fi

      export ANSIBLE_LOG_PATH
      mkdir -p $(dirname ${ANSIBLE_LOG_PATH})
      ansible-playbook  ${ANSIBLE_CLI_ARGS[@]}  ${ANSIBLE_DIR}/${ANSIBLE_FILE}
  artifacts:
    paths:
      - $ANSIBLE_LOG_PATH
    when: always
  retry: 2
  resource_group: ansible-run
