include:
  - local: .gitlab-ci/lib/defaults.gitlab-ci.yml
  - local: .gitlab-ci/lib/stages.gitlab-ci.yml
  - local: .gitlab-ci/lib/utilities.gitlab-ci.yml


# ============================================================================
.helm-base:
  before_script:
    - !reference [.utilities//load-all, script]
    - !reference [.helm//add-repos,     script]
    - |
      # --- helm-base --------------------------------------------------------
      helm dependency update ${HELM_CHART_DIR:-.}


# ============================================================================
.helm-package:
  stage: build
  extends: .helm-base
  script:
    - |
      # --- helm-package -----------------------------------------------------
      HELM_CHART_APP_VERSION=${GITLABCI_RELEASE_TRAIN:-${GITLABCI_SEMANTIC_VERSION}}

      JOB_SETTINGS_TABLE=()
      JOB_SETTINGS_TABLE+=("App version;${HELM_CHART_APP_VERSION}")
      JOB_SETTINGS_TABLE+=("Version;${GITLABCI_SEMANTIC_VERSION}")

      fn_print_settings_table "${JOB_SETTINGS_TABLE[@]}"

      mkdir -p .helm-package
      helm package  --app-version ${HELM_CHART_APP_VERSION}  \
                    --version     ${GITLABCI_SEMANTIC_VERSION}  \
                    --destination .helm-package  \
                    ${HELM_CHART_DIR:-.}
  artifacts:
    paths:
      - .helm-package
    when: always
    expire_in: 1 week


# ============================================================================
.helm-unit-test:
  stage: test
  extends: .helm-base
  script:
    - |
      # --- helm-unit-test ---------------------------------------------------
      mkdir -p .helm-unit-test
      helm unittest --file ${HELM_UNITTEST_FILE_GLOB:-'tests/*.tests.yaml'}  \
                    --output-type JUnit  \
                    --output-file .helm-unit-test/unit-test-results.${CI_JOB_ID}.xml  \
                    ${HELM_CHART_DIR:-.}
  artifacts:
    paths:
      - .helm-unit-test
    reports:
      junit: .helm-unit-test/unit-test-results.${CI_JOB_ID}.xml
    when: always
    expire_in: 1 week


# ============================================================================
.helm-push:
  stage: publish
  extends: .helm-base
  script:
    - |
      # --- helm-push --------------------------------------------------------
      HELM_CHART_NAME=$(helm show chart ${HELM_CHART_DIR} | grep -Po '^name:\s+\K.*')
      helm  cm-push   .helm-package/${HELM_CHART_NAME}-${GITLABCI_SEMANTIC_VERSION}.tgz  \
                      pipeline-push

      RELEASE_README_FILEPATH=.release/helm-chart.${CI_JOB_ID}.md
      mkdir -p $(dirname ${RELEASE_README_FILEPATH})

      # Convenience variables to make the code-block below a bit more readable:
      REPO_ALIAS=${CI_PROJECT_NAME}
      REPO_URL=${HELM_REPO_PIPELINE_PUSH_URL}
      CHART_ALIAS=${REPO_ALIAS}/${HELM_CHART_NAME}

      echo "### Helm Chart: ${HELM_CHART_NAME}"                           >> ${RELEASE_README_FILEPATH}
      echo ""                                                             >> ${RELEASE_README_FILEPATH}
      echo "\`\`\`bash"                                                   >> ${RELEASE_README_FILEPATH}
      echo "# Add the Helm repository:"                                   >> ${RELEASE_README_FILEPATH}
      echo "helm repo add ${REPO_ALIAS} ${REPO_URL}"                      >> ${RELEASE_README_FILEPATH}
      echo ""                                                             >> ${RELEASE_README_FILEPATH}
      echo "# Verify the new version (${GITLABCI_SEMANTIC_VERSION}) is available:" >> ${RELEASE_README_FILEPATH}
      echo "helm search repo --versions ${CHART_ALIAS}"                   >> ${RELEASE_README_FILEPATH}
      echo ""                                                             >> ${RELEASE_README_FILEPATH}
      echo "# If the latest version isn't available, update the repo:"    >> ${RELEASE_README_FILEPATH}
      echo "helm repo update ${REPO_ALIAS}"                               >> ${RELEASE_README_FILEPATH}
      echo ""                                                             >> ${RELEASE_README_FILEPATH}
      echo "# Customize your values, then install the Chart:"             >> ${RELEASE_README_FILEPATH}
      echo "helm install  --namespace <NAMESPACE>  \\"                    >> ${RELEASE_README_FILEPATH}
      echo "              --values <CONFIG_VALUES_FILE>  \\"              >> ${RELEASE_README_FILEPATH}
      echo "              <NAME>  \\"                                     >> ${RELEASE_README_FILEPATH}
      echo "              ${CHART_ALIAS}"                                 >> ${RELEASE_README_FILEPATH}
      echo "\`\`\`"                                                       >> ${RELEASE_README_FILEPATH}
  artifacts:
    paths:
      - .release


# ============================================================================
.helm//add-repos:
  script:
    - |
      # --- helm//add-repos --------------------------------------------------
      if [[ -z "${HELM_REPO_PIPELINE_PUSH_URL}" ]]; then
        HELM_REPO_PIPELINE_PUSH_URL=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
      fi

      if [[ -z "${HELM_REPO_PIPELINE_PUSH_USERNAME}" ]]; then
        HELM_REPO_PIPELINE_PUSH_USERNAME=gitlab-ci-token
      fi

      if [[ -z "${HELM_REPO_PIPELINE_PUSH_PASSWORD}" ]]; then
        HELM_REPO_PIPELINE_PUSH_PASSWORD=${CI_JOB_TOKEN}
      fi

      HELM_REPO_PIPELINE_PUSH_ALIAS_EXISTS=$(helm repo list 2> /dev/null | grep pipeline-push || true)
      if [[ -n "${HELM_REPO_PIPELINE_PUSH_ALIAS_EXISTS}" ]]; then
        helm repo remove pipeline-push
      fi

      for repo_url_varname in $(compgen -v HELM_REPO_); do
        if [[ "${repo_url_varname}" == *_URL ]]; then
          repo_varname_stem=${repo_url_varname#HELM_REPO_}
          repo_varname_stem=${repo_varname_stem/%_URL/}
          repo_username_var=HELM_REPO_${repo_varname_stem}_USERNAME
          repo_password_var=HELM_REPO_${repo_varname_stem}_PASSWORD

          repo_url=${!repo_url_varname}
          repo_alias=${repo_varname_stem,,}
          repo_alias=${repo_alias//_/-}
          repo_username=${!repo_username_var}
          repo_password=${!repo_password_var}

          helm_repo_add_cli_args=()

          if [[ -n "${repo_username}" ]]; then
            helm_repo_add_cli_args+=(--username ${repo_username})
          fi
          if [[ -n "${repo_password}" ]]; then
            helm_repo_add_cli_args+=(--password ${repo_password})
          fi

          helm_repo_add_cli_args+=(${repo_alias})
          helm_repo_add_cli_args+=(${repo_url})

          echo "Adding Helm repo: ${repo_alias} (${repo_url})"
          helm repo add ${helm_repo_add_cli_args[@]}
        fi
      done
