include:

  # --------------------------------------------------------------------------
  # Parent/base image
  - local: templates/image-pipeline.yml
    inputs:
      image_name: gitlab-ci/examples/parent
      jobs_suffix: " (parent)"
      image_build_context: examples/parent-child-images
      image_build_dockerfile: Dockerfile.parent
      image_unit_test_enabled: false
      image_structure_test_enabled: true
      image_structure_test_filenames:
        - examples/parent-child-images/image-structure-tests/parent.yaml


  # --------------------------------------------------------------------------
  # Child image:
  - local: templates/image-pipeline.yml
    inputs:
      image_name: gitlab-ci/examples/child
      jobs_suffix: " (child)"
      image_build_context: examples/parent-child-images
      image_build_dockerfile: Dockerfile.child
      image_build_parent_image_name: gitlab-ci/examples/parent
      image_unit_test_enabled: false
      image_build_needs:
        - image build (parent)
      image_structure_test_filenames:
        - examples/parent-child-images/image-structure-tests/child.yaml
